---
title: "SimulationOverview"
author: "Jesse"
date: "02/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simulate survival

The following chunks are demonstrating simulation


### basic followuptime simulation
```{r SimulateTime}
library(survival)
library(ggplot2)
library(casebase)
#basic follow up time
#followUpTime <- rweibull(30000, shape=4, scale=10)
#hist(followUpTime)

```



### simulating follow up time with censorship and covariates
```{r simulatetimecensWithCovariates, eval=FALSE}
simulWeibCens <- function(N, lambda, rho, beta, rateC)
{
  # covariate --> N Bernoulli trials
  x<-matrix(NA, N,length(beta))
  for(i in 1:length(beta)){
  x[,i] <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.7, 0.3))
  }
  
  # Weibull latent event times
  v <- runif(n=N)
  Tlat <- rowSums((- log(v) / (lambda * exp(x * beta)))^(1 / rho))
  browser()
  # censoring times
  C <- rexp(n=N, rate=rateC)

  # follow-up times and event indicators
  time <- pmin(Tlat, C)
  status <- as.numeric(Tlat <= C)

  # data set
  data.frame(id=1:N,
             time=time,
             status=status,
             x=x)
}



set.seed(1234)
obs<- 1
betas<-c(-0.6,0.5,10,-4)
betaHat <-matrix(NA, obs,length(betas))
for(k in 1:obs)
{
  dat <- simulWeibCens(N=1000, lambda=0.1, rho=1, beta=betas, rateC=0.1)
  fit <- coxph(Surv(time, status) ~ x.1+x.2+x.3, data=dat)
  cbFit<- fitSmoothHazard(status~log(time)+x.1+x.2+x.3,data=dat)
  abcb<-absoluteRisk(cbFit,newdata=dat,time=c(1:max(dat$time)))
  #betaHat[k,] <- fit$coef
  plot(survfit(fit),fun="event",col="red")
  lines(abcb[,1],rowMeans(abcb[,-c(1)]),type="l",col="blue")
}

```

```{r simulateNonProportionalHazardsWeibull,eval=FALSE}
simulExpCensNonProportional <- function(N, lambda, beta,timeDependentBetas, rateC)
{
  # covariate --> N Bernoulli trials
  x<-matrix(NA, N,length(beta))
  for(i in 1:length(beta)){
  x[,i] <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5))
  }
  
  xt<-matrix(NA,N,length(timeDependentBetas))
  for(i in 1:length(timeDependentBetas)){
  xt[,i] <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5))
  }
  
  # Weibull latent event times
  v <- runif(n=N)
 browser()
  Tlat <- rowSums(  log(abs((v*(xt*timeDependentBetas-lambda)/(lambda*exp(x*beta))) +1 )/(xt*timeDependentBetas-lambda))  )
  
  # censoring times
  C <- rexp(n=N, rate=rateC)

  # follow-up times and event indicators
  time <- pmin(Tlat, C)
  status <- as.numeric(Tlat <= C)

  # data set
  data.frame(id=1:N,
             time=time,
             status=status,
             x=x)
}

set.seed(1234)
obs<- 1
betas<-c(-0.6,0.5,10,-4)
timeBetas<-c(1,2,3,4)
betaHat <-matrix(NA, obs,length(betas))
for(k in 1:obs)
{
  dat <- simulExpCensNonProportional(N=1000, lambda=0.5, beta=betas,timeBetas, rateC=0.1)
  fit <- coxph(Surv(time, status) ~ x.1+x.2+x.3, data=dat)
  cbFit<- fitSmoothHazard(status~log(time)+x.1+x.2+x.3,data=dat)
  abcb<-absoluteRisk(cbFit,newdata=dat,time=c(1:max(dat$time)))
  #betaHat[k,] <- fit$coef
  plot(survfit(fit),fun="event",col="red")
  lines(abcb[,1],rowMeans(abcb[,-c(1)]),type="l",col="blue")
}


```

```{r simulateNonProportionalHazards,eval=TRUE}
simulGomCensNonProportional <- function(N, lambda,gamma, beta,timeDependentBetas, rateC)
{
  # covariate --> N Bernoulli trials
  x<-matrix(NA, N,length(beta))
  for(i in 1:length(beta)){
  x[,i] <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5))
  }
  
  xt<-matrix(NA,N,length(timeDependentBetas))
  for(i in 1:length(timeDependentBetas)){
  xt[,i] <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5))
  }
  
  # Weibull latent event times
  v <- runif(n=N)
  Tlat <- rowSums(  (1/(gamma+xt*timeDependentBetas))*log(-1*((gamma+xt*timeDependentBetas)/lambda*exp(x*beta))*log(v)+1)  )
  
  # censoring times
  C <- rexp(n=N, rate=rateC)

  # follow-up times and event indicators
  time <- pmin(Tlat, C)
  status <- as.numeric(Tlat <= C)

  # data set
  data.frame(id=1:N,
             time=time,
             status=status,
             x=x,xt=xt)
}

set.seed(1234)
obs<- 1
betas<-c(5,4,3,2,1,0.0001,0.0001,0.0001,0.0001,0.0001)
timeBetas<-c(5,4,3,2,1,0.0001,0.0001,0.0001,0.0001,0.0001)
betaHat <-matrix(NA, obs,length(betas))
for(k in 1:obs)
{
  dat <- simulGomCensNonProportional(N=1000, lambda=0.5,gamma=6, beta=betas,timeBetas, rateC=0.1)
 
}
#make random no association (abt 100)
#from full data, fit cox alone, then both cb and cox with regularization


  fit <- coxph(Surv(time, status) ~ x.1+x.2+x.3+x.4+xt.1*time+xt.2*time+xt.3*time+xt.4*time-time, data=dat)
  cbFit<- fitSmoothHazard(status~time+x.1+x.2+x.3+x.4+xt.1*time+xt.2*time+xt.3*time+xt.4*time,data=dat)
  abcb<-absoluteRisk(cbFit,newdata=dat,time=c(1:max(dat$time)))
  cbFit<- fitSmoothHazard(status~log(time)+x.1+x.2+x.3+x.4+xt.1*time+xt.2*time+xt.3*time+xt.4*time,data=dat)
  abcbwei<-absoluteRisk(cbFit,newdata=dat,time=c(1:max(dat$time)))
  betaHat[k,] <- fit$coef
  
  
  
  plot(survfit(fit),fun="event",col="red",lwd=2)
  lines(abcb[,1],rowMeans(abcb[,-c(1)]),type="l",col="blue",lwd=2)
  lines(abcbwei[,1],rowMeans(abcbwei[,-c(1)]),type="l",col="Black",lwd=2)
  legend("bottomright", legend=c("Cox", "Gompertz","Weibull"),
       col=c("red", "blue","black"), lty=1:2, cex=0.8)
  
 


```


```{r plotsForPresentation}
pt_object <- casebase::popTime(dat, event = "status",time="time")
plot(pt_object,add.case.series = FALSE,add.base.series = FALSE,ratio=0.5)
plot(pt_object,add.case.series = FALSE,add.base.series = TRUE,ratio=0.5,legend=TRUE)
plot(pt_object,add.base.series = TRUE,add.case.series = TRUE,ratio=0.5,legend=TRUE)

```


$$h(t|x)=\lambda e^{\gamma+\beta X +\beta_{t}X_{t}}$$

$$H(t|x)=\int_{0}^{t}h(u)du$$
$$U=exp[H(t|x))]=exp[- \frac{\lambda e^{\beta X}}{\gamma +\beta_{t}X_{t} }(e^{\gamma + \beta_{t}X_{t}t}-1) ]$$
$$ t=\frac{1}{\gamma + \beta_{t}X_{t}}*log(\frac{\gamma + \beta_{t}X_{t}}{\lambda e^{\beta X}} log(U)+1)$$

\begin{enumerate}
  \item $\lambda$ = shape
  \item $\gamma$ = scale 
  \item $\beta_{t}X_{t}$ = time-dependent linear predictors
  \item $\beta_{t}X_{t}$ = time-independent
  \item $U \sim U(0,1)$
  
\end{enumerate}

```{r censoringSimulations}

obs<- seq(0.01,0.9, by=0.1)
betas<-c(-0.6,0.5,10,-4)
timeBetas<-c(1,2,3,4)
betaHat <-matrix(NA, obs,length(betas))
curves<-matrix(NA, 1000,90)

k=1
  dat <- simulGomCensNonProportional(N=1000, lambda=0.5,gamma=6, beta=betas,timeBetas, rateC=obs[k])
  km<-survival::survfit(survival::Surv(time,status)~1,data=dat)
  colors<-RColorBrewer::brewer.pal(n = 9, name = 'YlOrRd')
  plot(x=km$time,y=1-km$surv,type="l",col=colors[9],lwd=2)
for(k in 2:length(obs))
{
  dat <- simulGomCensNonProportional(N=1000, lambda=0.5,gamma=6, beta=betas,timeBetas, rateC=obs[k])
  km<-survival::survfit(survival::Surv(time,status)~1,data=dat)
  lines(x=km$time,y=1-km$surv,type="l",col=colors[9-k+1],lwd=2)
  }

```